### ISSUE TITLE
Unable to use compiled library

### ISSUE THREAD

**Issue by fpfilko** [rollinhand/libdbf#1]
Hello,
I am able to compile the library, but I am unable to use it.
A simple program using this library, does not compile.
```
#include <libdbf/libdbf.h>
int main() {
    P_DBF *dbf = dbf_Open("test.dbf");
}
```
I use:
```
g++ main.cpp -ldbf
```
and it outputs:
```
/tmp/ccZl9I11.o: In function `main':
main.cpp:(.text+0x10): undefined reference to `dbf_Open(char const*)'
collect2: error: ld returned 1 exit status
```
Any ideas, what am I doing wrong?
Also, some example file using this library might help.
Thanks for any help!

**Comment by rollinhand** [comment]
Hi,
libdbf is the library which drives [dbf-core](https://github.com/rollinhand/dbf-core). You find an example on using libdbf in [main routines](https://github.com/rollinhand/dbf-core/blob/master/src/dbf.c) of dbf-core.

You also did not mention the system architecture you try to link libdbf to. Please note that library and code are about 11 years old and no longer under active development. Versions you find pre-compiled work only on 32-bit architectures on Intel machines.

I recommend to compile libdbf on your machine making sure it fits your architecture.

Kind regards,
Björn
